Convertir: Convertir.o Conversor.o Salida.o
				gcc -o Convertir Convertir.o Conversor.o Salida.o

Convertir.o: Convertir.c Conversor.h Salida.h
				gcc -g -Wall -c Convertir.c

Conversor.o: Conversor.c Conversor.h
				gcc -g -Wall -c Conversor.c

Salida.o: Salida.c Salida.h
				gcc -g -Wall -c Salida.c
				
